### ISSUE TITLE
Migration to new Rodan production

### ISSUE THREAD

**Issue by homework36** [DDMAL/Rodan#1137]
We have deleted the old GPU instance for Rodan production and relaunched a new one with smaller RAM so that we do not go over the current arbutus limit. We still need to configure the new instance to have the production Rodan back.
Here are a few things (and there might be more):
- [x] update to ubuntu 20.14 (now using ubuntu 22.04) (#1138)
- [x] install GPU driver and connect to cloud GPU (#1140)
- [x] set up from scratch
- [x] set up Nginx (#1142)
- [x] figure out the message below (now can be ignored since we don't use the old disk)
- [x] connect to ansible
- [ ] connect to grafana

```
A new version of /boot/grub/menu.lst is available, but the version installed currently 
has been locally modified. What would you like to do about menu.lst?       

   * install the package maintainer's version
   * keep the local version currently installed
   * show the differences between the versions
   * show a side-by-side difference between the versions
   * show a 3-way difference between available versions
   * do a 3-way merge between available versions (experimental)
   * start a new shell to examine the situation

  <Ok>
```

- [x] We are also missing two docker containers:
- rodan-gpu-celery
- rodan-python3-celery
